---
steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/hello_world
    entrypoint: bash
    args:
      - ../../scripts/prepreqs.sh
    env:
      - PROJECT=${PROJECT_ID}
      - REGION=${_REGION}
      - REPO=python

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    dir: functions/hello_world
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - hello_world
      - --project=${PROJECT_ID}
      - --region=${_REGION}
      - --runtime=python311
      - --trigger-http
      - -q
